# Generated by Django 3.0.8 on 2020-07-18 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('your_health', '0002_auto_20200707_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Imię')),
                ('surname', models.CharField(max_length=50, verbose_name='Nazwisko')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('userdata', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='your_health.UserData')),
            ],
        ),
    ]
