# Generated by Django 3.0.8 on 2020-07-06 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('your_health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_time', models.DateTimeField(auto_now_add=True)),
                ('systolic_pressure', models.SmallIntegerField(help_text='Ciśnienie skurczowe')),
                ('diastolic_pressure', models.SmallIntegerField(help_text='Ciśnienie rozkurczowe')),
                ('pulse', models.SmallIntegerField(help_text='Tętnop')),
                ('userdata', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='your_health.UserData')),
            ],
            options={
                'ordering': ['-measurement_time'],
            },
        ),
    ]
