# Generated by Django 3.0.8 on 2020-07-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='diastolic_pressure',
            field=models.SmallIntegerField(default=80, verbose_name='Ciśnienie rozkurczowe'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='pulse',
            field=models.SmallIntegerField(default=60, verbose_name='Tętno'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='systolic_pressure',
            field=models.SmallIntegerField(default=120, verbose_name='Ciśnienie skurczowe'),
        ),
    ]
