# Generated by Django 3.0.8 on 2020-07-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_auto_20200707_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measurement_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data pomiaru'),
        ),
    ]
