# Generated by Django 3.0.8 on 2020-07-04 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import your_health.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
                ('height', models.IntegerField(validators=[your_health.validators.min_height, your_health.validators.max_height])),
                ('weight', models.IntegerField(validators=[your_health.validators.min_weight, your_health.validators.max_weight])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
