# Generated by Django 3.0.8 on 2020-07-07 10:37

from django.db import migrations, models
import your_health.validators


class Migration(migrations.Migration):

    dependencies = [
        ('your_health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='height',
            field=models.IntegerField(validators=[your_health.validators.min_height, your_health.validators.max_height], verbose_name='Wzrost'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='sex',
            field=models.CharField(max_length=10, verbose_name='Płeć'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='weight',
            field=models.IntegerField(validators=[your_health.validators.min_weight, your_health.validators.max_weight], verbose_name='Waga'),
        ),
    ]
